
begin measurement "Shmem_Atomic_Fetch"
      measure comm_pt2pt : Shmem_Atomic_Fetch( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch( 5 )
end measurement

begin measurement "Shmem_Atomic_Fetch_Inc"
      measure comm_pt2pt : Shmem_Atomic_Fetch_Inc( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch_Inc"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch_Inc( 5 )
end measurement

begin measurement "Shmem_Atomic_Swap"
      measure comm_pt2pt : Shmem_Atomic_Swap( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Swap"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Swap( 5 )
end measurement

begin measurement "Shmem_Atomic_Fetch_Add"
      measure comm_pt2pt : Shmem_Atomic_Fetch_Add( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch_Add"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch_Add( 5 )
end measurement

begin measurement "Shmem_Atomic_Fetch_And"
      measure comm_pt2pt : Shmem_Atomic_Fetch_And( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch_And"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch_And( 5 )
end measurement

begin measurement "Shmem_Atomic_Fetch_Or"
      measure comm_pt2pt : Shmem_Atomic_Fetch_Or( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch_Or"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch_Or( 5 )
end measurement

begin measurement "Shmem_Atomic_Fetch_Xor"
      measure comm_pt2pt : Shmem_Atomic_Fetch_Xor( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Fetch_Xor"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Fetch_Xor( 5 )
end measurement

begin measurement "Shmem_Atomic_Compare_Swap_Yes"
      measure comm_pt2pt : Shmem_Atomic_Compare_Swap_Yes( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Compare_Swap_Yes"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Compare_Swap_Yes( 5 )
end measurement

begin measurement "Shmem_Atomic_Compare_Swap_No"
      measure comm_pt2pt : Shmem_Atomic_Compare_Swap_No( 5 )
end measurement

begin measurement "Shmem_Ctx_Atomic_Compare_Swap_No"
      measure comm_pt2pt : Shmem_Ctx_Atomic_Compare_Swap_No( 5 )
end measurement

